### PR TITLE
fix(indicators): extend custom functionality - INNO-405

### PR DESCRIPTION
**Pull request by kalinchernev**
Extending the existing function with optional configuration.

### CODE REVIEW

**Comment by kalinchernev** [comment]
@emeryro could you please also drop an eye for the implementation for the delay if it's flexible enough?

**Comment by yhuard** [comment]
More important would be to trigger the animation only when the element is visible in the viewport! 

Feasible with https://github.com/terwanerik/ScrollTrigger#callbacks

**Comment by emeryro** [comment]
Yes, I thought about it.
It could be an improvement

**Comment by kalinchernev** [comment]
Hi @yhuard @emeryro thanks for the reviews so far!
Just pushed an update to handle delay incrementally.
Any other suggestions - please share!

**Pull request merged**
