### PR TITLE
fix(bugs): fix various bugs - INNO-627

### PR DESCRIPTION
**Pull request by yhuard**

### CODE REVIEW

**Comment by yhuard** [comment]
Please update the markup of the title (_main page pictures_)

```html
      <h1 class="ecl-h1">
        <a href="#" class="ffa-text-shadow section__title-link">Addressing root causes of irregular migration and instability in numbers</a>
      </h1>
```

**Comment by yhuard** [comment]
`Links > All links should be in lowercase letters (ie. "About the EUTF", "About the strategy", "More news & stories")` in those cases, just remove the class `.ffa-text-uppercase`

**Comment by kalinchernev** [comment]
About the issue
```
Navigation Page
Change font "Explore our projects" & drop-down menus (see mock-up, align on other pages)
```
The markup structure needs to be updated as following:
```html
<h2 class="ecl-h2 ecl-pt-none ffa-text-center ffa-text-primary">
  <form action="/multisite/euetfa/navigation/region_en" method="post" id="-euetfa-project-navigation-filter-form" accept-charset="UTF-8">
    <div>
      <label for="edit-nav-filter" style="
        display: inline-block;
        font-weight: normal;
        ">Explore our projects by </label>
      <div class="ffa-select ffa-text-default">
        <select onchange="this.form.submit();" class="form-control form-select" id="edit-nav-filter" name="nav_filter">
          <option value="region" selected="selected">Regions and Countries</option>
          <option value="theme">Themes</option>
          <option value="partner">Partners</option>
        </select>
      </div>
    </div>
  </form>
</h2>
```
Steps:
- `select` must be wrapped around `ffa-select ffa-text-default`
- `label` must be before this wrapper in order to avoid the underline of the select

**Comment by yhuard** [comment]
`Navigation page > Windows title should not be underlined`

The class `.ffa-link` is missing on the link [here](https://webgate.acceptance.ec.europa.eu/multisite/euetfa/navigation/region_en). Please add it to fix this issue

**Comment by yhuard** [comment]
`Project pages > Project title should be aligned on the left`: please remove the class `ffa-text-center` of the title

**Comment by yhuard** [comment]
`Project pages > Align geographical areas`: please put all the regions in the same `<dd>`

Now:

```html
  <dt class="ecl-col-5">Location</dt>
  <dd class="ecl-col-7">Adamaoua</dd>
  <dd class="ecl-col-7">Extrême-Nord</dd>
  <dd class="ecl-col-7">Nord</dd>
```

Should be: 

```html
  <dt class="ecl-col-5">Location</dt>
  <dd class="ecl-col-7">Adamaoua, Extrême-Nord, Nord</dd>
```

Seen on https://webgate.acceptance.ec.europa.eu/multisite/euetfa/content/projet-dappui-%C3%A0-la-r%C3%A9silience-socio-%C3%A9conomique-des-jeunes-vuln%C3%A9rables-extr%C3%AAme-nord-nord-et_en

**Pull request merged**
